blank_issues_enabled: true

contact_links:
  - name: 上游项目讨论区
    url: https://github.com/Ferry-200/coriander_player/discussions
    about: 上游项目的讨论区（原始作者维护）
  - name: 提交空白 Issue
    url: https://github.com/reneryi/qisheng_player/issues/new
    about: 如果你的问题不属于以上模板类型，可以创建空白 Issue