// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `average_bucket`, `channel`, `color_distance_sq`, `median_cut`, `widest_channel`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RgbSample`, `WeightedColor`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`

/// for Flutter
/// 从图片原始字节中提取稳定的 RGB 主色列表，返回值不包含 alpha。
Future<Uint32List> extractDominantColors(
        {required List<int> imageBytes, required int maxColors}) =>
    RustLib.instance.api.crateApiAlbumPaletteExtractDominantColors(
        imageBytes: imageBytes, maxColors: maxColors);
