// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cleanup`, `fields`, `fingerprint`, `snapshot_json`, `synchronize`, `transactions`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Transaction`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`

Future<AudioMetadataSnapshot> readAudioMetadata({required String path}) =>
    RustLib.instance.api.crateApiMetadataEditorReadAudioMetadata(path: path);

/// Returns an opaque token. A second prepare for the same physical file fails.
Future<String> prepareAudioMetadata(
        {required String path,
        required String supportPath,
        required String expectedFingerprint,
        required AudioMetadataPatch patch}) =>
    RustLib.instance.api.crateApiMetadataEditorPrepareAudioMetadata(
        path: path,
        supportPath: supportPath,
        expectedFingerprint: expectedFingerprint,
        patch: patch);

/// Called while the playback handle is released. The journal is already durable.
Future<AudioMetadataSnapshot> commitAudioMetadata({required String token}) =>
    RustLib.instance.api
        .crateApiMetadataEditorCommitAudioMetadata(token: token);

Future<AudioMetadataSnapshot> finishAudioMetadata(
        {required String token, required String supportPath}) =>
    RustLib.instance.api.crateApiMetadataEditorFinishAudioMetadata(
        token: token, supportPath: supportPath);

Future<void> cancelAudioMetadata({required String token}) =>
    RustLib.instance.api
        .crateApiMetadataEditorCancelAudioMetadata(token: token);

/// Invoked before loading the index on startup, before overrides are read.
Future<List<String>> recoverAudioMetadata({required String supportPath}) =>
    RustLib.instance.api
        .crateApiMetadataEditorRecoverAudioMetadata(supportPath: supportPath);

/// None keeps a field, an empty string clears it. Zero clears an ordinal.
class AudioMetadataPatch {
  final String? title;
  final String? artist;
  final String? album;
  final String? albumArtist;
  final int? track;
  final int? disc;
  final String? lyrics;
  final Uint8List? cover;

  const AudioMetadataPatch({
    this.title,
    this.artist,
    this.album,
    this.albumArtist,
    this.track,
    this.disc,
    this.lyrics,
    this.cover,
  });

  static Future<AudioMetadataPatch> default_() =>
      RustLib.instance.api.crateApiMetadataEditorAudioMetadataPatchDefault();

  @override
  int get hashCode =>
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      albumArtist.hashCode ^
      track.hashCode ^
      disc.hashCode ^
      lyrics.hashCode ^
      cover.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioMetadataPatch &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          albumArtist == other.albumArtist &&
          track == other.track &&
          disc == other.disc &&
          lyrics == other.lyrics &&
          cover == other.cover;
}

class AudioMetadataSnapshot {
  final String title;
  final String artist;
  final String album;
  final String albumArtist;
  final int track;
  final int disc;
  final String lyrics;
  final BigInt modified;
  final BigInt size;
  final String fingerprint;

  const AudioMetadataSnapshot({
    required this.title,
    required this.artist,
    required this.album,
    required this.albumArtist,
    required this.track,
    required this.disc,
    required this.lyrics,
    required this.modified,
    required this.size,
    required this.fingerprint,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      albumArtist.hashCode ^
      track.hashCode ^
      disc.hashCode ^
      lyrics.hashCode ^
      modified.hashCode ^
      size.hashCode ^
      fingerprint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioMetadataSnapshot &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          albumArtist == other.albumArtist &&
          track == other.track &&
          disc == other.disc &&
          lyrics == other.lyrics &&
          modified == other.modified &&
          size == other.size &&
          fingerprint == other.fingerprint;
}
